version: 2.1
jobs:
  print-token:
    docker:
      - image: cimg/node:10.16.3
    steps:
      # Install jwt parsing tool
      - run: npm install -g jwt-cli
      # Parse the token and print it
      - run: echo $CIRCLE_OIDC_TOKEN | rev
  hell:
    docker:
      - image: cimg/node:10
    steps:
      - run: echo boom

workflows:
  print:
    jobs:
      - print-token
      - hell
