on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: teken
      run: echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | rev
